# Generated by Django 4.2.11 on 2024-03-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='create_at',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
